Use connection manager for keepalives
glencoesoftware/omero2pandas pull request #20
Opened 2024-07-31 15:36 UTC by DavidStirling

Fixes #18

For now we'll use our own keepalive runner making use of the omero2pandas session manager, since the one built into omero.client struggles to shut down properly.

2024-08-01 16:25 UTC, chris-allan requested changes
I'm not sure about this. It effectively recapitulates and effectively works against what the omero-py client object and service factory already do. We should talk this through more to understand what's going on.

2024-08-05 13:12 UTC, chris-allan commented
Relevant upstream PR is ome/omero-py#424.

2024-08-07 09:19 UTC, chris-allan approved these changes
Going to approve this for now so it can go in temporarily for as long as it's required.

We will need to work to get ome/omero-py#424 in as soon as possible and then follow up here refactoring as required and depending explicitly on the omero-py version that includes that change.

This PR will be for @erindiel, @sbesson and @emilroz to get integrated and shipping as required for other work next week.

2024-08-26 15:05 UTC, merged

2024-09-16 15:33 UTC, sbesson commented
[omero-py 5.19.5](https://github.com/ome/omero-py/blob/v5.19.5/CHANGELOG.md) has just been released with the corresponding upstream fix